### ISSUE TITLE
failed to open window

### ISSUE THREAD

**Issue by certik** [progschj/OpenGL-Examples#4]
All examples just say:

```
ondrej@eagle:~/repos/OpenGL-Examples/build(master)$ ./00skeleton 
failed to open window
```

It's caused by this part:

``` c++
    // create a window
    GLFWwindow *window;
    if((window = glfwCreateWindow(width, height, "00skeleton", 0, 0)) == 0) {
        std::cerr << "failed to open window" << std::endl;
        glfwTerminate();
        return 1;
    }
```

But I don't know how to fix it.

**Comment by progschj** [comment]
What does "glxinfo | grep version" (glxinfo is in the mesa-util package) tell you? My best guess from the limited information is that you don't have a OpenGL 3.3 capable card/driver.

**Comment by certik** [comment]
It says:

```
$ glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL version string: 2.1 Mesa 10.1.3
OpenGL shading language version string: 1.20
```

So I guess I have OpenGL version 2.1? According to this: https://www.opengl.org/wiki/History_of_OpenGL#OpenGL_2.1_.282006.29, that's 9 years old...  I bought my laptop in 2011, so I didn't realize the OpenGL is so old.

Thanks for your help.

**Comment by larspensjo** [comment]
I think the problem is that you are using the Open Source Mesa drivers. If you instead install the proprietary drivers for the graphics card, you will get a much more recent version of OpenGL. These are not installed by default on most Linux platforms.
