### ISSUE TITLE
failed to open window

### ISSUE THREAD

**Issue by MartinThoma** [progschj/OpenGL-Examples#7]
When I try to execute the compiled examples (e.g. `01shader_vbo1`) I only get

```
failed to open window
```

Do you have any idea what the problem might be?

**Comment by progschj** [comment]
Insufficient OpenGL versions are the most likely cause. That specific 
example should require 3.3. What gl version (try "glxinfo | grep 
version" on linux), gpu or driver are you using?

Am 25.02.2016 12:13, schrieb Martin Thoma:

**Comment by MartinThoma** [comment]
Ok, that was the problem.

``` bash
glxinfo | grep version                                                                                       
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL version string: 2.1 Mesa 11.3.0-devel (git-9d9aeb9 2016-02-25 wily-oibaf-ppa)
OpenGL shading language version string: 1.20
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 11.3.0-devel (git-9d9aeb9 2016-02-25 wily-oibaf-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```

This laptop does not have a GPU (Intel HD Graphics). When I used it on my tower, it worked :-)

You could add a requirements section to the README.md.
